# Generated by Django 4.1.7 on 2023-03-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='user_profile/photos/default.png', upload_to='user_profile/photos/', verbose_name='photo'),
        ),
    ]
